
LEAF_KEY_ID="leaf"
LEAF_DISTINGUISHED_NAME="CN=${LEAF_KEY_ID}"

# 'STORE' is always a 'file' so '_FILE' suffix is not necessary ('STORE_FILE')
LEAF_JKS_KEY_STORE="${LEAF_KEY_ID}_keystore.jks"
LEAF_P12_KEY_STORE="${LEAF_KEY_ID}_keystore.p12"

LEAF_KEY_STORE="${LEAF_JKS_KEY_STORE}"
#LEAF_KEY_STORE="${LEAF_P12_KEY_STORE}"

#LEAF_JKS_KEY_STORE_OPTION="-keystore ${LEAF_JKS_KEY_STORE}"
#LEAF_P12_KEY_STORE_OPTION="-keystore ${LEAF_P12_KEY_STORE}"

#LEAF_KEY_STORE_OPTION="${LEAF_JKS_KEY_STORE_OPTION}"
#LEAF_KEY_STORE_OPTION="${LEAF_P12_KEY_STORE_OPTION}"

LEAF_KEY_STORE_OPTION="-keystore ${LEAF_KEY_STORE}"

# Note: 'pkcs#12' expects both 'keystore password' and 'key password' to be equal

#LEAF_PASSWORD="LEAF_PASSWORD"
LEAF_PASSWORD_FILE="PASSWORDs/${LEAF_KEY_ID}_PASSWORD.txt"

#LEAF_KEY_STORE_PASSWORD_OPTION="-storepass ${LEAF_PASSWORD}"
LEAF_KEY_STORE_PASSWORD_OPTION="-storepass:file ${LEAF_PASSWORD_FILE}"

#LEAF_KEY_PASSWORD_OPTION="-storepass ${LEAF_PASSWORD}"
LEAF_KEY_PASSWORD_OPTION="-keypass:file ${LEAF_PASSWORD_FILE}"
