
ROOT_CA_KEY_ID="root_CA"
ROOT_CA_DISTINGUISHED_NAME="CN=${ROOT_CA_KEY_ID}"

# 'STORE' is always a 'file' so '_FILE' suffix is not necessary ('STORE_FILE')
ROOT_CA_KEY_STORE="${ROOT_CA_KEY_ID}_keystore.jks"
#ROOT_CA_KEY_STORE_PASSWORD="ROOT_CA_KEY_STORE_PASSWORD"
ROOT_CA_KEY_STORE_PASSWORD_FILE="${ROOT_CA_KEY_ID}_KEY_STORE_PASSWORD.txt"

ROOT_CA_KEY_STORE_OPTION="-keystore ${ROOT_CA_KEY_STORE}"
#ROOT_CA_KEY_STORE_PASSWORD_OPTION="-storepass ${ROOT_CA_KEY_STORE_PASSWORD}"
ROOT_CA_KEY_STORE_PASSWORD_OPTION="-storepass:file ${ROOT_CA_KEY_STORE_PASSWORD_FILE}"


#ROOT_CA_KEY_PASSWORD="ROOT_CA_KEY_PASSWORD"
ROOT_CA_KEY_PASSWORD_FILE="${ROOT_CA_KEY_ID}_KEY_PASSWORD.txt"

ROOT_CA_KEY_OPTION="-keystore ${ROOT_CA_KEY_STORE}"
#ROOT_CA_KEY_PASSWORD_OPTION="-storepass ${ROOT_CA_KEY_PASSWORD}"
ROOT_CA_KEY_PASSWORD_OPTION="-keypass:file ${ROOT_CA_KEY_PASSWORD_FILE}"
