
SUB_CA_KEY_ID="sub_CA"
SUB_CA_DISTINGUISHED_NAME="CN=${SUB_CA_KEY_ID}"

# 'STORE' is always a 'file' so '_FILE' suffix is not necessary ('STORE_FILE')
SUB_CA_KEY_STORE="${SUB_CA_KEY_ID}_keystore.jks"
#SUB_CA_KEY_STORE_PASSWORD="SUB_CA_KEY_STORE_PASSWORD"
SUB_CA_KEY_STORE_PASSWORD_FILE="PASSWORDs/${SUB_CA_KEY_ID}_KEY_STORE_PASSWORD.txt"

SUB_CA_KEY_STORE_OPTION="-keystore ${SUB_CA_KEY_STORE}"
#SUB_CA_KEY_STORE_PASSWORD_OPTION="-storepass ${SUB_CA_KEY_STORE_PASSWORD}"
SUB_CA_KEY_STORE_PASSWORD_OPTION="-storepass:file ${SUB_CA_KEY_STORE_PASSWORD_FILE}"


#SUB_CA_KEY_PASSWORD="SUB_CA_KEY_PASSWORD"
SUB_CA_KEY_PASSWORD_FILE="PASSWORDs/${SUB_CA_KEY_ID}_KEY_PASSWORD.txt"

SUB_CA_KEY_OPTION="-keystore ${SUB_CA_KEY_STORE}"
#SUB_CA_KEY_PASSWORD_OPTION="-storepass ${SUB_CA_KEY_PASSWORD}"
SUB_CA_KEY_PASSWORD_OPTION="-keypass:file ${SUB_CA_KEY_PASSWORD_FILE}"
